name: Chaindata Build

on:
  # runs after each push to current branch
  push:
  # can be run manually from the `Actions` tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow pushing commits
permissions:
  contents: write
  id-token: write

concurrency:
  # only run 1 job per branch/pr/etc at a time
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  publish:
    name: 'Build & publish chaindata to dist folder'
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build chaindata
        run: pnpm build
      - name: Commit changes
        env:
          CHAINDATA_CI_SUPERUSER_ACCESS_TOKEN: ${{ secrets.CHAINDATA_CI_SUPERUSER_ACCESS_TOKEN }}
        run: |
          git config --local --unset-all 'http.https://github.com/.extraheader'
          git remote set-url origin https://x-access-token:${CHAINDATA_CI_SUPERUSER_ACCESS_TOKEN}@github.com/TalismanSociety/chaindata
          git config user.name "chaindata-ci-superuser[bot]"
          git config user.email "146698419+chaindata-ci-superuser[bot]@users.noreply.github.com"
          if [[ "$(git status --porcelain=v2)" != "" ]]; then
            git add .
            git commit -m 'chore: built chaindata'
            git push
          fi
