name: Chaindata Fetch External

on:
  # runs at `0 minutes past the hour, every 6 hours`, starting at midnight UTC
  schedule:
    - cron: '0 0/6 * * *'
  # can be run manually from the `Actions` tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow pushing commits
permissions:
  contents: write
  id-token: write

concurrency:
  # only run 1 job per branch/pr/etc at a time
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  publish:
    name: 'Fetch externals and push changes to repo'
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Fetch external
        run: pnpm fetch-external
      - name: Commit changes
        run: |
          git remote set-url origin https://x-access-token:${CHAINDATA_CI_SUPERUSER_ACCESS_TOKEN}@github.com/TalismanSociety/chaindata
          git config user.name "chaindata-ci-superuser[bot]"
          git config user.email "146698419+chaindata-ci-superuser[bot]@users.noreply.github.com"
          git add .
          git commit -m 'updated externals'
          git push
